### Load Relevant Libraries

In [3]:
import folium
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
from shapely.geometry import MultiLineString, LineString, Point
from shapely.ops import nearest_points
from shapely.wkt import loads as load_wkt
from shapely.ops import unary_union
import math
import numpy as np
import pyproj
from flask import Flask, render_template, jsonify, request

### Load in Data

In [4]:
data_dir = "Bus_RoutesStopsServices"
trunkroutes = pd.read_csv(f"{data_dir}/trunkroutes.csv")

In [5]:
grouped_train_lines = gpd.read_file("TrainStation_Jul2024/mrt_lines_shapefile.shp")
grouped_train_lines = grouped_train_lines.groupby('MRT_LINE')

mrt_lines_list = []  

# Create  LineString for each MRT Line
for MRT_LINE, group in grouped_train_lines:
    group_sorted = group.sort_values('STN_SEQUEN')
    coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
    mrt_lines_list.append(LineString(coordinates))

# Merge into one MultiLineString > The entire MRT System as one MultiLineString
mrt_multiline = MultiLineString(mrt_lines_list)

/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()
/var/folders/06/3zsj3_kd48n_rbnyhcxkz01c0000gn/T/ipykernel_6494/2757938163.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.y, geom.x)).tolist()

### Calculative Functions

In [6]:
def haversine(coord1, coord2): # computes distance between two points on the surface of a sphere using the latitude and longitude 
    R = 6371.0  # radius of earth in kilometers
    lat1, lon1 = math.radians(coord1[0]), math.radians(coord1[1])
    lat2, lon2 = math.radians(coord2[0]), math.radians(coord2[1])
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c

def calculate_bearing(coord1, coord2): # computes the bearing between two line segments to measure how parallel they are
    lat1, lon1 = np.radians(coord1)
    lat2, lon2 = np.radians(coord2)
    delta_lon = lon2 - lon1
    x = np.sin(delta_lon) * np.cos(lat2)
    y = np.cos(lat1) * np.sin(lat2) - (np.sin(lat1) * np.cos(lat2) * np.cos(delta_lon))
    bearing = np.degrees(np.arctan2(x, y))
    return (bearing + 360) % 360

In [7]:
def calculate_route_parallelism(bus_route_line, mrt_multiline):
    total_score = 0
    segment_scores = []
    total_length = 0  

    # Loop through each segment in the bus route
    for i in range(len(bus_route_line.coords) - 1):

        # Define the start and end points of the bus segment
        bus_segment = LineString([bus_route_line.coords[i], bus_route_line.coords[i + 1]])
        bus_bearing = calculate_bearing(bus_route_line.coords[i], bus_route_line.coords[i + 1])
        
        # Calculate the length of the bus segment (in meters)
        segment_length = haversine(bus_route_line.coords[i], bus_route_line.coords[i + 1]) * 1000 #convert from km to m
        total_length += segment_length

        # Find the nearest MRT line segment to this bus segment
        min_distance = float('inf')
        nearest_mrt_bearing = None

        # Loop through each MRT line segment in the MRT network
        for mrt_line in mrt_multiline.geoms:
            for j in range(len(mrt_line.coords) - 1):
                mrt_segment = LineString([mrt_line.coords[j], mrt_line.coords[j + 1]])
                mrt_bearing = calculate_bearing(mrt_line.coords[j], mrt_line.coords[j + 1])

                # Find the minimum distance from the bus segment to the MRT segment
                p1, p2 = nearest_points(bus_segment, mrt_segment)
                distance = haversine((p1.y, p1.x), (p2.y, p2.x)) * 1000 #convert from km to m

                if distance < min_distance:
                    min_distance = distance
                    nearest_mrt_bearing = mrt_bearing

        # Calculate the bearing difference between the bus segment and nearest MRT segment
        bearing_diff = abs(bus_bearing - nearest_mrt_bearing)
        if bearing_diff > 180:
            bearing_diff = 360 - bearing_diff

        # Calculate the parallelism score for this segment, considering both distance and bearing difference
        score = (1 / (1 + min_distance)) * (1 - bearing_diff / 180)  # Score decreases as distance or bearing diff increases

        # Weight the score by the segment length but smooth its influence by scaling
        # Using sqrt(segment_length) to reduce the influence of very long segments without a hard cap
        weighted_score = score * np.sqrt(segment_length)
        segment_scores.append(weighted_score)
        total_score += weighted_score

    # Normalise the total score by the square root of the total route length
    ## Smooths out the impact of route length and avoids inflating scores for shorter routes
    normalised_score = total_score / np.sqrt(total_length) if total_length > 0 else 0

    return normalised_score

### Generate Parallelism Score

In [8]:
# Read in bus LineString csv
line_string_df = pd.read_csv('Bus_RoutesStopsServices/bus_linestring.csv') 

parallelism_results = []

unique_services = line_string_df['ServiceNo'].unique()

for service_no in unique_services:
    # Get the LINESTRING for the current bus service
    bus_route_line = load_wkt(line_string_df[line_string_df['ServiceNo'] == service_no]['LineString'].values[0])
    
    # Calculate Parallel score for current bus service 
    parallel_score = calculate_route_parallelism(bus_route_line, mrt_multiline)
    
    parallelism_results.append({
        'ServiceNo': service_no,
        'ParallelismScore': parallel_score
    })

# Store all scores in a dataframe
parallelism_df = pd.DataFrame(parallelism_results)
parallelism_df = parallelism_df.sort_values(by='ParallelismScore', ascending=False)

print(parallelism_df)

/Users/lilyrozana/Documents/GitHub/DSA4264/venv/lib/python3.11/site-packages/shapely/linear.py:203: RuntimeWarning: invalid value encountered in shortest_line
  return lib.shortest_line(a, b, **kwargs)

KeyboardInterrupt:

In [8]:
# Save Step1 Parallelism Score to .csv for easy reference
parallelism_df.to_csv("Bus_RoutesStopsServices/parallel_score_step1.csv", index=False)

## Changes After Consultation:
* #1 if other bus services go through similar route, high proportion of buses going through similar route > higher parallel score
* #2 if bus route is parallel to more than one mrt line, lower parallel score

## Step 2: if bus route is parallel to more than one mrt line, lower parallel score

### Convert each MRT Line to a LineString and build a buffer around each line

In [10]:
mrt_lines = gpd.read_file("TrainStation_Jul2024/mrt_lines_shapefile.shp") # Read in MRT Lines .shp file

mrt_lines = mrt_lines.to_crs(epsg=3414) # reproject to a projected CRS

# group by MRT line and create buffers around each line
grouped_train_lines = mrt_lines.groupby('MRT_LINE')
mrt_buffers = {}

# Create a 1 km buffer for each MRT line 
for MRT_LINE, group in grouped_train_lines:
    group_sorted = group.sort_values('STN_SEQUEN')
    coordinates = group_sorted['geometry'].centroid.apply(lambda geom: (geom.x, geom.y)).tolist()
    line_string = LineString(coordinates)
    buffer = line_string.buffer(1000)  # 1000 meters (1 km buffer)
    mrt_buffers[MRT_LINE] = buffer

# filter mrt_buffers to remove duplicates
mrt_buffers = {key: buffer for key, buffer in mrt_buffers.items() if not key.endswith('.')}

### For each Bus Service, count how many and which MRT Lines it is parallel to

#### Method : An MRT line will only be counted  if there is at least one unique segment of at least 8 consecutive bus stops within its buffer, without overlapping into buffers of other lines unless those additional stops independently satisfy the "8 consecutive stops" rule
#### 1. Track Consecutive Stops per MRT Line: Ensure each MRT line only counts a segment if there are 8+ consecutive stops in its buffer.
#### 2. Prevent Overlapping Segment Counts: If a segment meets the 8-stop requirement for one MRT line but overlaps with another line, only count it for the primary MRT line and reset the counter for overlapping lines until they have 8+ consecutive stops independently.

In [11]:
# Load bus stop data and filter for ServiceNo of trunk buses
step1_parallel_score = pd.read_csv('Bus_RoutesStopsServices/parallel_score_step1.csv')
relevant_services = step1_parallel_score['ServiceNo']

# Load bus stop data and create geometry column
bus_data = pd.read_csv('Bus_RoutesStopsServices/all_bus_data.csv')
bus_data = bus_data[bus_data['ServiceNo'].isin(relevant_services)]  # Filter for relevant ServiceNo
bus_data['geometry'] = bus_data.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
bus_stops_gdf = gpd.GeoDataFrame(bus_data, geometry='geometry', crs="EPSG:4326")

# Reproject bus stops to the same CRS as MRT buffers
bus_stops_gdf = bus_stops_gdf.to_crs("EPSG:3414")  

# Initialise a dictionary to store segment counts for each ServiceNo and MRT line
parallelism_counts = {}

# Loop over each bus ServiceNo to find segments close to each MRT line buffer
for service_no, stops in bus_stops_gdf.groupby('ServiceNo'):
    stops = stops.sort_values('StopSequence')  # sort by StopSequence to ensure order
    service_counts = {line: 0 for line in mrt_buffers.keys()}  # initialize count for each MRT line
    
    # Loop through each MRT line and check for valid segments within its buffer
    for mrt_line, buffer in mrt_buffers.items():
        consecutive_count = 0  # track consecutive stops within the buffer
        already_counted = False  # ensure each qualifying segment is counted once per MRT line

        # Iterate over stops in sequence
        for i in range(len(stops)):
            stop_point = stops.iloc[i]['geometry']
            
            # Check if the current stop is within the MRT buffer
            if stop_point.within(buffer):
                consecutive_count += 1  # increment consecutive count within buffer
                
                # Check if we have hit 5 consecutive stops within buffer
                if consecutive_count >= 8 and not already_counted:
                    service_counts[mrt_line] = 1  # set to 1 for this MRT line
                    already_counted = True  # mark as counted for this segment
            else:
                # Reset count if stop is outside buffer and reset the count flag for a new segment
                consecutive_count = 0
                already_counted = False  # allow new segment to be counted when condition met again

    # Store binary values for the current service_no > simply indicate if that MRT Line is close to that bus service
    parallelism_counts[service_no] = service_counts

# Convert results to a DataFrame
trunkbus_mrt_counts = pd.DataFrame.from_dict(parallelism_counts, orient='index').reset_index()
trunkbus_mrt_counts = trunkbus_mrt_counts.rename(columns={'index': 'ServiceNo'})

# Add a Total Count Column to see how many MRT Lines are parallel to each bus service
mrt_columns = ["Circle Line", "Downtown Line", "East-West Line", "North-East Line", "North-South Line", "Thomson-East Coast Line"]
trunkbus_mrt_counts["Total Count"] = trunkbus_mrt_counts[mrt_columns].sum(axis=1)


trunkbus_mrt_counts

,ServiceNo,Circle Line,Downtown Line,East-West Line,North-East Line,North-South Line,Thomson-East Coast Line,Total Count
0,10,1,1,1,1,0,1,5
1,100,1,1,1,1,1,0,5
2,100A,0,0,0,0,0,0,0
3,101,0,0,0,1,0,0,1
4,102,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...
397,991C,0,0,0,0,0,0,0
398,992,0,0,0,0,0,0,0
399,993,0,0,0,0,0,0,0
400,9A,0,1,1,0,0,0,2
401,9B,0,1,0,0,0,0,1

### Merge trunkbus_mrt_counts with dataframe from Step 1 and apply penalty for buses parallel to more than one MRT Line

In [12]:
trunkbus_mrt_counts = trunkbus_mrt_counts[["ServiceNo", "Total Count"]]
merged_step1and2 = pd.merge(step1_parallel_score, trunkbus_mrt_counts, on="ServiceNo", how="left")

In [13]:
# Function to calculate the penalty based on "Total Count"
def calculate_penalty(total_count):
    if total_count == 1:
        return 1
    elif total_count == 2:
        return 0.9
    elif total_count == 3:
        return 0.8
    elif total_count == 4:
        return 0.7
    elif total_count == 5:
        return 0.6
    elif total_count == 6:
        return 0.5
    else:
        return 1 

# Apply the penalty function and calculate the "Step 2 Parallelism Score"
merged_step1and2["Step 2 Parallelism Score"] = (
    merged_step1and2["ParallelismScore"] * 
    merged_step1and2["Total Count"].apply(calculate_penalty)
)

# Sort by Step 2 Parallelism Score and get new ranking
merged_step1and2 = merged_step1and2.sort_values(by='Step 2 Parallelism Score', ascending=False)
merged_step1and2['Rank'] = merged_step1and2['Step 2 Parallelism Score'].rank(method="dense", ascending=False).astype(int)


# To view how much ranking has changed after adding penalty for routes that are parallel to more than one MRT Line
merged_step1and2.head(20)

   ServiceNo  ParallelismScore  Total Count  Step 2 Parallelism Score  Rank
25       966          1.621423            1                  1.621423     1
0         63          2.249656            5                  1.349793     2
49       858          1.346868            1                  1.346868     3
2         48          2.176651            5                  1.305991     4
30        31          1.587173            3                  1.269739     5
3        970          2.106962            5                  1.264177     6
18       158          1.752099            4                  1.226470     7
50       170          1.345928            2                  1.211335     8
19       196          1.710318            4                  1.197222     9
70        27          1.161053            1                  1.161053    10
6         36          1.925217            5                  1.155130    11
23        16          1.646013            4                  1.152209    12
76       200          1.145214            1                  1.145214    13
77       168          1.142945            1                  1.142945    14
24       16M          1.627856            4                  1.139499    15
80       161          1.128188            1                  1.128188    16
7        36B          1.877460            5                  1.126476    17
58        24          1.248825            2                  1.123942    18
8        63A          1.872791            5                  1.123674    19
11        67          1.820436            5                  1.092262    20

In [14]:
# Tidy up columns for step2_parallel_score
step2_parallel_score = merged_step1and2[["ServiceNo", "Step 2 Parallelism Score", "Rank"]]

# Save step2_parallel_score to .csv for easy reference
step2_parallel_score.to_csv("Bus_RoutesStopsServices/parallel_score_step2.csv", index=False)
step2_parallel_score.head(20)

   ServiceNo  Step 2 Parallelism Score  Rank
25       966                  1.621423     1
0         63                  1.349793     2
49       858                  1.346868     3
2         48                  1.305991     4
30        31                  1.269739     5
3        970                  1.264177     6
18       158                  1.226470     7
50       170                  1.211335     8
19       196                  1.197222     9
70        27                  1.161053    10
6         36                  1.155130    11
23        16                  1.152209    12
76       200                  1.145214    13
77       168                  1.142945    14
24       16M                  1.139499    15
80       161                  1.128188    16
7        36B                  1.126476    17
58        24                  1.123942    18
8        63A                  1.123674    19
11        67                  1.092262    20

## Step 3: Check the popularity of trunk services: higher popularity, higher parallel score

#### Method: Check the proportion of other bus services that go through each trunk route
#### 1. Count the number of other buses that go through more than 30% of that trunk route
#### 2. Penalise score based on how many other buses go through similar bus stops in that trunk service

In [16]:
trunkroutes = pd.read_csv("Bus_RoutesStopsServices/trunkroutes.csv")
bus_routes = pd.read_csv("Bus_RoutesStopsServices/bus_routes.csv")
step2_parallel_score = pd.read_csv("Bus_RoutesStopsServices/parallel_score_step2.csv")

In [36]:
# Group by 'ServiceNo' and aggregate 'BusStopCode' into a list for each unique service
all_bus_stops_dict = {}
for service_no, group in bus_routes.groupby('ServiceNo'):
    # Ensure the key is stored as a string, not a tuple
    all_bus_stops_dict[str(service_no)] = group['BusStopCode'].tolist()

def get_counts(BusNo):
    # Get the list of bus stops for the specified BusNo 
    bus_stops = all_bus_stops_dict.get(BusNo)
    
    # Check if bus_stops is None, meaning BusNo is not in the dictionary
    if bus_stops is None:
        print(f"Bus number {BusNo} not found in all_bus_stops_dict.")
        return 0
    
    # Convert bus_stops to a set for intersection operations
    bus_stops_set = set(bus_stops)
    
    # Initialize the proportion dictionary
    proportion = {}
    
    # Loop over all other bus services to calculate the proportion of common stops
    for other_bus, other_stops in all_bus_stops_dict.items():
        # Skip if it's the same bus service
        if other_bus == BusNo:
            continue
        
        # Convert other_stops to a set and calculate the intersection of bus stops
        other_stops_set = set(other_stops)
        common_stops = bus_stops_set.intersection(other_stops_set)
        
        # Calculate the proportion of shared stops with respect to BusNo
        proportion[other_bus] = len(common_stops) / len(bus_stops_set) if len(bus_stops_set) > 0 else 0

    # Count the number of bus services that share more than 30% of stops with BusNo
    count = sum(1 for val in proportion.values() if val > 0.3)
    
    return count

bus_stop_counts = {}
# Loop over each unique ServiceNo in all_bus_services or bus_routes
for service_no in all_bus_stops_dict.keys():
    # Call get_counts for each service_no and store the result in bus_stop_counts
    bus_stop_counts[service_no] = get_counts(service_no)

In [39]:
def get_step3_parallel_score(step2):

    step3_parallel_score = step2.rename(columns={'Step 2 Parallelism Score':'ParallelismScore'}).drop(columns=["Rank"])
    
    # Apply the transformation based on the value in bus_stop_counts
    for index, row in step3_parallel_score.iterrows():
        service_no = row['ServiceNo']
        parallelism_score = row['ParallelismScore']
        
        # Check if the ServiceNo exists in bus_stop_counts
        count = bus_stop_counts.get(service_no, 0)  # Default to 0 if ServiceNo is not in bus_stop_counts

        # Modify the ParallelismScore based on the count value
        if count == 0:
            step3_parallel_score.at[index, 'ParallelismScore'] = parallelism_score * 1
        elif count == 1:
            step3_parallel_score.at[index, 'ParallelismScore'] = parallelism_score * 1.1
        elif count == 2:
            step3_parallel_score.at[index, 'ParallelismScore'] = parallelism_score * 1.2
        else:  # count >= 3
            step3_parallel_score.at[index, 'ParallelismScore'] = parallelism_score * 1.3

        step3_parallel_score.sort_values(by='ParallelismScore', ascending=False).reset_index().drop(columns=["index"])
        step3_parallel_score['Rank'] = step3_parallel_score.index + 1
    return step3_parallel_score

In [40]:
step3_parallel_score = get_step3_parallel_score(step2_parallel_score)
step3_parallel_score.to_csv("Bus_RoutesStopsServices/parallel_score_step3.csv", index=False)
step3_parallel_score.head(20)

   ServiceNo  ParallelismScore  Rank
0        966          1.783565     1
1         63          1.754731     2
2        858          1.616241     3
3         48          1.567189     4
4         31          1.650660     5
5        970          1.264177     6
6        158          1.471763     7
7        170          1.574735     8
8        196          1.316945     9
9         27          1.509369    10
10        36          1.501670    11
11        16          1.497872    12
12       200          1.488779    13
13       168          1.257240    14
14       16M          1.481349    15
15       161          1.466645    16
16       36B          1.464419    17
17        24          1.461125    18
18       63A          1.460777    19
19        67          1.419940    20

### Normalise Score to a range of [0,1]

In [41]:
min_score = step3_parallel_score['ParallelismScore'].min()
max_score = step3_parallel_score['ParallelismScore'].max()

step3_parallel_score['Score'] = ((step3_parallel_score['ParallelismScore'] - min_score) / (max_score - min_score)).round(2)
step3_parallel_score['Rank'] = step3_parallel_score['Score'].rank(method="dense", ascending=False).astype(int)

step3_parallel_score = step3_parallel_score[['ServiceNo', 'Score', 'Rank']]
step3_parallel_score

    ServiceNo  Score  Rank
0         966   1.00     1
1          63   0.98     2
2         858   0.91     4
3          48   0.88     5
4          31   0.93     3
..        ...    ...   ...
397         6   0.00    89
398      127A   0.00    89
399      973A   0.00    89
400       68A   0.00    89
401       88B   0.00    89

[402 rows x 3 columns]

In [ ]:
step3_parallel_score .to_csv("Bus_RoutesStopsServices/paralleltrunkservicesranked.csv", index=False)